// frontend/admin-frontend/src/layouts/AdminLayout.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useRoute, useRouter } from 'vue-router';

const route = useRoute();
const router = useRouter();

const navItems = [
  { to: '/', label: 'Dashboard', exact: true },
  { to: '/users', label: 'Users' },
  { to: '/roles', label: 'Roles' },
  { to: '/memberships', label: 'Memberships' },
  { to: '/seller-approvals', label: 'Seller Approvals' },
  { to: '/audit-log', label: 'Audit Log' },
];

const isActive = (path: string, exact = false) => {
  if (exact) return route.path === path;
  return route.path.startsWith(path);
};

const navigate = (path: string) => {
  router.push(path);
};

const isEmbedded = computed(() => (window as any).__POWERED_BY_PORTAL_SHELL__ === true);
</script>

<template>
  <div class="flex min-h-screen">
    <!-- Admin Sidebar (only in standalone mode; embedded uses portal-shell sidebar) -->
    <aside
      v-if="!isEmbedded"
      class="w-56 bg-bg-card border-r border-border-default flex flex-col shrink-0"
    >
      <div class="p-4 text-lg font-bold text-text-heading border-b border-border-default">
        Portal Admin
      </div>
      <nav class="flex-1 p-2 space-y-1">
        <button
          v-for="item in navItems"
          :key="item.to"
          @click="navigate(item.to)"
          :class="[
            'block w-full text-left px-3 py-2 rounded text-sm transition-colors',
            isActive(item.to, item.exact)
              ? 'bg-brand-primary/10 text-brand-primary font-medium'
              : 'text-text-body hover:bg-bg-elevated'
          ]"
        >
          {{ item.label }}
        </button>
      </nav>
    </aside>

    <!-- Main Content -->
    <main class="flex-1 p-6 overflow-auto">
      <router-view />
    </main>
  </div>
</template>

// frontend/shopping-frontend/src/components/layout/AdminLayout.tsx
/**
 * Admin Layout
 * Admin 페이지를 위한 공통 레이아웃
 */
import React, { useState } from 'react'
import { Outlet, Link, useLocation } from 'react-router-dom'
import { useAuthStore } from '@/stores/authStore'

interface NavItem {
  label: string
  path: string
  icon: React.ReactNode
}

const navItems: NavItem[] = [
  {
    label: 'Products',
    path: '/admin/products',
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
      </svg>
    )
  }
]

export const AdminLayout: React.FC = () => {
  const location = useLocation()
  const { user, logout } = useAuthStore()
  const [sidebarOpen, setSidebarOpen] = useState(true)

  const handleLogout = () => {
    logout()
    window.location.href = '/'
  }

  return (
    <div className="min-h-screen bg-bg-page">
      {/* Header */}
      <header className="fixed top-0 left-0 right-0 z-50 h-16 bg-bg-card border-b border-border-default flex items-center justify-between px-6 shadow-sm">
        {/* Logo & Title */}
        <div className="flex items-center gap-3">
          <button
            onClick={() => setSidebarOpen(!sidebarOpen)}
            className="lg:hidden w-10 h-10 flex items-center justify-center text-text-body hover:text-brand-primary transition-colors"
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
            </svg>
          </button>

          <div className="w-8 h-8 bg-brand-primary rounded-lg flex items-center justify-center">
            <span className="text-white font-bold text-sm">A</span>
          </div>
          <h1 className="text-xl font-bold text-text-heading">Admin Portal</h1>
        </div>

        {/* User Menu */}
        <div className="flex items-center gap-4">
          <span className="text-sm text-text-meta">
            Welcome, <span className="font-medium text-text-heading">{user?.name || 'Admin'}</span>
          </span>
          <button
            onClick={handleLogout}
            className="px-4 py-2 text-sm font-medium text-status-error hover:text-status-error/80 transition-colors"
          >
            Logout
          </button>
        </div>
      </header>

      {/* Sidebar */}
      <aside
        className={`
          fixed left-0 top-16 bottom-0 w-64
          bg-bg-card border-r border-border-default
          overflow-y-auto transition-transform duration-300
          ${sidebarOpen ? 'translate-x-0' : '-translate-x-full'}
          lg:translate-x-0
          z-40
        `}
      >
        <nav className="p-4 space-y-2">
          {navItems.map((item) => {
            const isActive = location.pathname.startsWith(item.path)
            return (
              <Link
                key={item.path}
                to={item.path}
                className={`
                  flex items-center gap-3 px-4 py-3 rounded-lg
                  transition-colors
                  ${isActive
                    ? 'bg-brand-primary/10 text-brand-primary font-medium'
                    : 'text-text-body hover:bg-bg-hover'
                  }
                `}
              >
                {item.icon}
                {item.label}
              </Link>
            )
          })}
        </nav>
      </aside>

      {/* Main Content */}
      <main className={`transition-all duration-300 ${sidebarOpen ? 'lg:ml-64' : ''} mt-16 min-h-screen p-6 lg:p-8`}>
        <Outlet />
      </main>

      {/* Overlay for mobile */}
      {sidebarOpen && (
        <div
          className="fixed inset-0 bg-gray-900/50 z-30 lg:hidden"
          onClick={() => setSidebarOpen(false)}
        />
      )}
    </div>
  )
}

export default AdminLayout
