// frontend/shopping-frontend/src/components/common/Button.tsx
/**
 * Button Component
 * Admin UI에서 사용하는 버튼 컴포넌트
 */
import React from 'react'

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary' | 'ghost' | 'danger'
  loading?: boolean
  icon?: React.ReactNode
  fullWidth?: boolean
}

export const Button: React.FC<ButtonProps> = ({
  children,
  variant = 'primary',
  loading = false,
  icon,
  fullWidth = false,
  className = '',
  disabled,
  ...props
}) => {
  const baseStyles = 'px-6 py-3 rounded-lg font-medium transition-all duration-200 flex items-center justify-center gap-2'

  const variantStyles = {
    primary: 'bg-brand-primary text-white hover:bg-brand-primaryHover shadow-sm hover:shadow-md',
    secondary: 'border-2 border-brand-primary bg-transparent text-brand-primary hover:bg-brand-primary/5',
    ghost: 'bg-transparent text-text-body hover:bg-bg-hover',
    danger: 'bg-status-error text-white hover:bg-status-error/90 shadow-sm hover:shadow-md'
  }

  const disabledStyles = 'disabled:opacity-50 disabled:cursor-not-allowed'
  const fullWidthStyles = fullWidth ? 'w-full' : ''

  return (
    <button
      className={`${baseStyles} ${variantStyles[variant]} ${disabledStyles} ${fullWidthStyles} ${className}`}
      disabled={disabled || loading}
      {...props}
    >
      {loading ? (
        <>
          <div className="w-5 h-5 border-2 border-current border-t-transparent rounded-full animate-spin" />
          <span>Loading...</span>
        </>
      ) : (
        <>
          {icon && icon}
          {children}
        </>
      )}
    </button>
  )
}

export default Button

// frontend/design-system/src/components/Button/Button.vue
<script setup lang="ts">
import type { ButtonProps } from './Button.types';

const props = withDefaults(defineProps<ButtonProps>(), {
  variant: 'primary',
  size: 'md',
  disabled: false
});

// Linear-inspired button styles
const variantClasses = {
  // Primary: Light button on dark bg (Linear style)
  primary: [
    'bg-[#e6e6e6] text-[#08090a]',
    'hover:bg-white',
    'active:bg-[#d4d4d4]',
    'border border-transparent'
  ].join(' '),
  // Secondary: Subtle transparent button
  secondary: [
    'bg-transparent text-text-meta',
    'hover:bg-bg-hover hover:text-text-body',
    'active:bg-bg-muted',
    'border border-border-default'
  ].join(' '),
  // Ghost: Minimal button
  ghost: [
    'bg-transparent text-text-meta',
    'hover:bg-bg-hover hover:text-text-body',
    'active:bg-bg-muted',
    'border border-transparent'
  ].join(' '),
  // Outline: Border only
  outline: [
    'bg-transparent text-text-body',
    'hover:bg-bg-hover',
    'active:bg-bg-muted',
    'border border-border-default hover:border-border-hover'
  ].join(' '),
  // Danger: Destructive action
  danger: [
    'bg-status-error text-white',
    'hover:bg-red-600',
    'active:bg-red-700',
    'border border-transparent'
  ].join(' ')
};

const sizeClasses = {
  xs: 'px-2 py-1 text-xs',
  sm: 'px-3 py-1.5 text-sm',
  md: 'px-4 py-2 text-sm',
  lg: 'px-5 py-2.5 text-base'
};
</script>

<template>
  <button
    :class="[
      'inline-flex items-center justify-center gap-2',
      'font-medium rounded-md',
      'transition-all duration-[160ms] ease-[cubic-bezier(0.25,0.1,0.25,1)]',
      'focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-primary focus-visible:ring-offset-2 focus-visible:ring-offset-bg-page',
      variantClasses[variant],
      sizeClasses[size],
      { 'opacity-50 cursor-not-allowed pointer-events-none': disabled }
    ]"
    :disabled="disabled"
  >
    <slot />
  </button>
</template>
