// frontend/design-system-react/src/components/Button/Button.tsx
import { forwardRef, type ButtonHTMLAttributes, type ReactNode } from 'react';
import type { ButtonProps } from '@portal/design-types';
import { cn } from '../../utils/cn';
import { Spinner } from '../Spinner';

export interface ButtonComponentProps
  extends ButtonProps,
    Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'type'> {
  children?: ReactNode;
}

const variantClasses: Record<NonNullable<ButtonProps['variant']>, string> = {
  primary:
    'bg-brand-primary text-text-inverse hover:bg-brand-primaryHover active:bg-brand-primaryHover',
  secondary:
    'bg-bg-muted text-text-body hover:bg-bg-hover border border-border-default',
  ghost: 'bg-transparent text-text-body hover:bg-bg-hover',
  outline:
    'bg-transparent text-text-body border border-border-default hover:bg-bg-hover hover:border-border-hover',
  danger:
    'bg-status-error text-white hover:bg-red-600 active:bg-red-700',
};

const sizeClasses: Record<NonNullable<ButtonProps['size']>, string> = {
  xs: 'h-6 px-2 text-xs gap-1',
  sm: 'h-8 px-3 text-sm gap-1.5',
  md: 'h-9 px-4 text-base gap-2',
  lg: 'h-11 px-6 text-lg gap-2',
};

export const Button = forwardRef<HTMLButtonElement, ButtonComponentProps>(
  (
    {
      variant = 'primary',
      size = 'md',
      disabled,
      loading,
      fullWidth,
      type = 'button',
      className,
      children,
      ...props
    },
    ref
  ) => {
    const isDisabled = disabled || loading;

    return (
      <button
        ref={ref}
        type={type}
        disabled={isDisabled}
        className={cn(
          // Base styles
          'inline-flex items-center justify-center font-medium rounded-md',
          'transition-all duration-normal ease-linear-ease',
          'focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-primary focus-visible:ring-offset-2',
          // Variant
          variantClasses[variant],
          // Size
          sizeClasses[size],
          // Full width
          fullWidth && 'w-full',
          // Disabled state
          isDisabled && 'opacity-50 cursor-not-allowed',
          className
        )}
        {...props}
      >
        {loading && <Spinner size="sm" color="current" className="shrink-0" />}
        {children}
      </button>
    );
  }
);

Button.displayName = 'Button';

export default Button;

// frontend/design-system/src/components/Button/Button.vue
<script setup lang="ts">
import type { ButtonProps } from './Button.types';

const props = withDefaults(defineProps<ButtonProps>(), {
  variant: 'primary',
  size: 'md',
  disabled: false
});

// Linear-inspired button styles
const variantClasses = {
  // Primary: Light button on dark bg (Linear style)
  primary: [
    'bg-[#e6e6e6] text-[#08090a]',
    'hover:bg-white',
    'active:bg-[#d4d4d4]',
    'border border-transparent'
  ].join(' '),
  // Secondary: Subtle transparent button
  secondary: [
    'bg-transparent text-text-meta',
    'hover:bg-bg-hover hover:text-text-body',
    'active:bg-bg-muted',
    'border border-border-default'
  ].join(' '),
  // Ghost: Minimal button
  ghost: [
    'bg-transparent text-text-meta',
    'hover:bg-bg-hover hover:text-text-body',
    'active:bg-bg-muted',
    'border border-transparent'
  ].join(' '),
  // Outline: Border only
  outline: [
    'bg-transparent text-text-body',
    'hover:bg-bg-hover',
    'active:bg-bg-muted',
    'border border-border-default hover:border-border-hover'
  ].join(' '),
  // Danger: Destructive action
  danger: [
    'bg-status-error text-white',
    'hover:bg-red-600',
    'active:bg-red-700',
    'border border-transparent'
  ].join(' ')
};

const sizeClasses = {
  xs: 'px-2 py-1 text-xs',
  sm: 'px-3 py-1.5 text-sm',
  md: 'px-4 py-2 text-sm',
  lg: 'px-5 py-2.5 text-base'
};
</script>

<template>
  <button
    :class="[
      'inline-flex items-center justify-center gap-2',
      'font-medium rounded-md',
      'transition-all duration-[160ms] ease-[cubic-bezier(0.25,0.1,0.25,1)]',
      'focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-primary focus-visible:ring-offset-2 focus-visible:ring-offset-bg-page',
      variantClasses[variant],
      sizeClasses[size],
      { 'opacity-50 cursor-not-allowed pointer-events-none': disabled }
    ]"
    :disabled="disabled"
  >
    <slot />
  </button>
</template>
