// frontend/design-system/src/components/Input/Input.vue
<script setup lang="ts">
import type { InputProps } from './Input.types';

const props = withDefaults(defineProps<InputProps>(), {
  type: 'text',
  modelValue: '',
  placeholder: '',
  disabled: false,
  error: false,
  errorMessage: '',
  label: '',
  required: false,
  size: 'md'
});

const emit = defineEmits<{
  'update:modelValue': [value: string | number]
}>();

function handleInput(event: Event) {
  const target = event.target as HTMLInputElement;
  emit('update:modelValue', target.value);
}

const sizeClasses = {
  sm: 'px-3 py-1.5 text-sm',
  md: 'px-3 py-2 text-sm',
  lg: 'px-4 py-2.5 text-base'
};
</script>

<template>
  <div class="input-wrapper">
    <!-- Label -->
    <label
      v-if="label"
      class="block text-sm font-medium text-text-body mb-1.5"
    >
      {{ label }}
      <span v-if="required" class="text-status-error ml-0.5">*</span>
    </label>

    <!-- Input -->
    <input
      :type="type"
      :value="modelValue"
      :placeholder="placeholder"
      :disabled="disabled"
      @input="handleInput"
      :class="[
        'w-full rounded-md',
        'bg-transparent',
        'border',
        'text-text-body placeholder:text-text-muted',
        'transition-all duration-[160ms] ease-[cubic-bezier(0.25,0.1,0.25,1)]',
        'focus:outline-none focus:ring-2 focus:ring-brand-primary/20',
        sizeClasses[size],
        error
          ? 'border-status-error focus:border-status-error'
          : 'border-border-default focus:border-brand-primary hover:border-border-hover',
        disabled && 'bg-bg-muted cursor-not-allowed opacity-50'
      ]"
    />

    <!-- Error Message -->
    <p
      v-if="error && errorMessage"
      class="mt-1.5 text-sm text-status-error"
    >
      {{ errorMessage }}
    </p>
  </div>
</template>

// frontend/design-system-react/src/components/Input/Input.tsx
import { forwardRef, type InputHTMLAttributes, useId } from 'react';
import type { InputProps } from '@portal/design-types';
import { cn } from '../../utils/cn';

export interface InputComponentProps
  extends Omit<InputProps, 'value'>,
    Omit<InputHTMLAttributes<HTMLInputElement>, 'size' | 'type'> {}

const sizeClasses: Record<NonNullable<InputProps['size']>, string> = {
  sm: 'h-8 px-3 text-sm',
  md: 'h-9 px-3 text-base',
  lg: 'h-11 px-4 text-lg',
};

export const Input = forwardRef<HTMLInputElement, InputComponentProps>(
  (
    {
      type = 'text',
      placeholder,
      disabled,
      error,
      errorMessage,
      label,
      required,
      size = 'md',
      id: providedId,
      className,
      ...props
    },
    ref
  ) => {
    const generatedId = useId();
    const id = providedId || generatedId;

    return (
      <div className="w-full">
        {label && (
          <label
            htmlFor={id}
            className={cn(
              'block mb-1.5 text-sm font-medium text-text-body',
              disabled && 'opacity-50'
            )}
          >
            {label}
            {required && <span className="text-status-error ml-0.5">*</span>}
          </label>
        )}
        <input
          ref={ref}
          type={type}
          id={id}
          disabled={disabled}
          placeholder={placeholder}
          aria-invalid={error}
          aria-describedby={error && errorMessage ? `${id}-error` : undefined}
          className={cn(
            // Base styles
            'w-full rounded-md border bg-bg-card text-text-body placeholder:text-text-muted',
            'transition-all duration-normal ease-linear-ease',
            'focus:outline-none focus:ring-2 focus:ring-brand-primary focus:border-transparent',
            // Size
            sizeClasses[size],
            // Error state
            error
              ? 'border-status-error focus:ring-status-error'
              : 'border-border-default hover:border-border-hover',
            // Disabled state
            disabled && 'opacity-50 cursor-not-allowed bg-bg-muted',
            className
          )}
          {...props}
        />
        {error && errorMessage && (
          <p id={`${id}-error`} className="mt-1.5 text-sm text-status-error">
            {errorMessage}
          </p>
        )}
      </div>
    );
  }
);

Input.displayName = 'Input';

export default Input;
