// frontend/design-react/src/components/Pagination/Pagination.tsx
import { forwardRef, type HTMLAttributes } from 'react';
import type { PaginationProps } from '@portal/design-core';
import { cn } from '@portal/design-core';
import { Button } from '../Button';

export interface PaginationComponentProps
  extends PaginationProps,
    Omit<HTMLAttributes<HTMLElement>, 'onChange'> {
  onChange?: (page: number) => void;
}

const sizeClasses: Record<NonNullable<PaginationProps['size']>, string> = {
  sm: 'text-xs',
  md: 'text-sm',
  lg: 'text-base',
};

export const Pagination = forwardRef<HTMLElement, PaginationComponentProps>(
  (
    {
      page,
      totalPages,
      siblingCount = 1,
      showFirstLast = true,
      size = 'md',
      onChange,
      className,
      ...props
    },
    ref
  ) => {
    const getPageNumbers = () => {
      const pages: (number | 'ellipsis')[] = [];
      const leftSiblingIndex = Math.max(page - siblingCount, 1);
      const rightSiblingIndex = Math.min(page + siblingCount, totalPages);

      const showLeftEllipsis = leftSiblingIndex > 2;
      const showRightEllipsis = rightSiblingIndex < totalPages - 1;

      if (showFirstLast || !showLeftEllipsis) {
        pages.push(1);
      }

      if (showLeftEllipsis) {
        pages.push('ellipsis');
      }

      for (let i = leftSiblingIndex; i <= rightSiblingIndex; i++) {
        if (i !== 1 && i !== totalPages) {
          pages.push(i);
        }
      }

      if (showRightEllipsis) {
        pages.push('ellipsis');
      }

      if ((showFirstLast || !showRightEllipsis) && totalPages > 1) {
        pages.push(totalPages);
      }

      return pages;
    };

    const buttonSize = size === 'sm' ? 'xs' : size === 'lg' ? 'md' : 'sm';

    return (
      <nav
        ref={ref}
        role="navigation"
        aria-label="Pagination"
        className={cn('flex items-center gap-1', sizeClasses[size], className)}
        {...props}
      >
        <Button
          variant="ghost"
          size={buttonSize}
          disabled={page <= 1}
          onClick={() => onChange?.(page - 1)}
          aria-label="Previous page"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
          </svg>
        </Button>

        {getPageNumbers().map((pageNumber, index) => {
          if (pageNumber === 'ellipsis') {
            return (
              <span
                key={`ellipsis-${index}`}
                className="px-2 text-text-muted"
              >
                ...
              </span>
            );
          }

          return (
            <Button
              key={pageNumber}
              variant={page === pageNumber ? 'primary' : 'ghost'}
              size={buttonSize}
              onClick={() => onChange?.(pageNumber)}
              aria-label={`Page ${pageNumber}`}
              aria-current={page === pageNumber ? 'page' : undefined}
            >
              {pageNumber}
            </Button>
          );
        })}

        <Button
          variant="ghost"
          size={buttonSize}
          disabled={page >= totalPages}
          onClick={() => onChange?.(page + 1)}
          aria-label="Next page"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
          </svg>
        </Button>
      </nav>
    );
  }
);

Pagination.displayName = 'Pagination';

export default Pagination;

// frontend/design-vue/src/components/Pagination/Pagination.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { PaginationProps } from '@portal/design-core';

const props = withDefaults(defineProps<PaginationProps & { modelValue?: number }>(), {
  siblingCount: 1,
  showFirstLast: true,
  size: 'md',
});

const emit = defineEmits<{
  'update:modelValue': [value: number];
  change: [value: number];
}>();

const currentPage = computed(() => props.modelValue ?? props.page);

const sizeMap: Record<string, string> = {
  sm: 'h-7 w-7 text-xs',
  md: 'h-8 w-8 text-sm',
  lg: 'h-10 w-10 text-base',
};

const pages = computed(() => {
  const total = props.totalPages;
  const current = currentPage.value;
  const siblings = props.siblingCount;
  const result: (number | 'ellipsis')[] = [];

  const leftSibling = Math.max(current - siblings, 1);
  const rightSibling = Math.min(current + siblings, total);

  const showLeftEllipsis = leftSibling > 2;
  const showRightEllipsis = rightSibling < total - 1;

  if (!showLeftEllipsis && showRightEllipsis) {
    const leftRange = 1 + 2 * siblings + 1;
    for (let i = 1; i <= Math.min(leftRange, total); i++) result.push(i);
    if (leftRange < total) {
      result.push('ellipsis');
      result.push(total);
    }
  } else if (showLeftEllipsis && !showRightEllipsis) {
    result.push(1);
    const rightRange = total - (2 * siblings + 1);
    if (rightRange > 1) result.push('ellipsis');
    for (let i = Math.max(rightRange + 1, 2); i <= total; i++) result.push(i);
  } else if (showLeftEllipsis && showRightEllipsis) {
    result.push(1);
    result.push('ellipsis');
    for (let i = leftSibling; i <= rightSibling; i++) result.push(i);
    result.push('ellipsis');
    result.push(total);
  } else {
    for (let i = 1; i <= total; i++) result.push(i);
  }

  return result;
});

const goToPage = (page: number) => {
  if (page < 1 || page > props.totalPages || page === currentPage.value) return;
  emit('update:modelValue', page);
  emit('change', page);
};
</script>

<template>
  <nav role="navigation" aria-label="Pagination">
    <ul class="flex items-center gap-1">
      <!-- First -->
      <li v-if="showFirstLast">
        <button
          type="button"
          :disabled="currentPage <= 1"
          :class="[
            'inline-flex items-center justify-center rounded-md transition-colors',
            sizeMap[size],
            currentPage <= 1
              ? 'text-text-muted cursor-not-allowed'
              : 'text-text-body hover:bg-bg-hover',
          ]"
          aria-label="First page"
          @click="goToPage(1)"
        >
          <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M11 19l-7-7 7-7m8 14l-7-7 7-7" />
          </svg>
        </button>
      </li>

      <!-- Previous -->
      <li>
        <button
          type="button"
          :disabled="currentPage <= 1"
          :class="[
            'inline-flex items-center justify-center rounded-md transition-colors',
            sizeMap[size],
            currentPage <= 1
              ? 'text-text-muted cursor-not-allowed'
              : 'text-text-body hover:bg-bg-hover',
          ]"
          aria-label="Previous page"
          @click="goToPage(currentPage - 1)"
        >
          <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15 19l-7-7 7-7" />
          </svg>
        </button>
      </li>

      <!-- Pages -->
      <li v-for="(item, index) in pages" :key="index">
        <span
          v-if="item === 'ellipsis'"
          :class="['inline-flex items-center justify-center text-text-muted', sizeMap[size]]"
        >
          ...
        </span>
        <button
          v-else
          type="button"
          :aria-current="item === currentPage ? 'page' : undefined"
          :class="[
            'inline-flex items-center justify-center rounded-md font-medium transition-colors',
            sizeMap[size],
            item === currentPage
              ? 'bg-brand-primary text-white'
              : 'text-text-body hover:bg-bg-hover',
          ]"
          @click="goToPage(item as number)"
        >
          {{ item }}
        </button>
      </li>

      <!-- Next -->
      <li>
        <button
          type="button"
          :disabled="currentPage >= totalPages"
          :class="[
            'inline-flex items-center justify-center rounded-md transition-colors',
            sizeMap[size],
            currentPage >= totalPages
              ? 'text-text-muted cursor-not-allowed'
              : 'text-text-body hover:bg-bg-hover',
          ]"
          aria-label="Next page"
          @click="goToPage(currentPage + 1)"
        >
          <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9 5l7 7-7 7" />
          </svg>
        </button>
      </li>

      <!-- Last -->
      <li v-if="showFirstLast">
        <button
          type="button"
          :disabled="currentPage >= totalPages"
          :class="[
            'inline-flex items-center justify-center rounded-md transition-colors',
            sizeMap[size],
            currentPage >= totalPages
              ? 'text-text-muted cursor-not-allowed'
              : 'text-text-body hover:bg-bg-hover',
          ]"
          aria-label="Last page"
          @click="goToPage(totalPages)"
        >
          <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M13 5l7 7-7 7M5 5l7 7-7 7" />
          </svg>
        </button>
      </li>
    </ul>
  </nav>
</template>
