// frontend/portal-shell/src/views/ForbiddenPage.vue
<script setup lang="ts">
import { useRouter } from 'vue-router'
import { Card, Button } from '@portal/design-system-vue'

const router = useRouter()
</script>

<template>
  <div class="min-h-[calc(100vh-200px)] flex items-center justify-center p-4 bg-bg-page">
    <Card variant="elevated" padding="lg" class="w-full max-w-2xl">
      <div class="text-center py-12">
        <div class="text-8xl mb-6">🚫</div>
        <div class="text-6xl font-bold text-status-error mb-4">403</div>
        <h1 class="text-3xl font-bold text-text-heading mb-3">
          접근 권한이 없습니다
        </h1>
        <p class="text-lg text-text-meta mb-8 max-w-md mx-auto">
          이 페이지에 접근할 수 있는 권한이 부족합니다.<br />
          필요한 권한이 있다면 관리자에게 문의해 주세요.
        </p>
        <div class="flex flex-wrap gap-3 justify-center">
          <Button variant="primary" size="lg" @click="router.push('/')">
            홈으로 이동
          </Button>
          <Button variant="secondary" size="lg" @click="router.back()">
            이전 페이지
          </Button>
        </div>
      </div>
    </Card>
  </div>
</template>

// frontend/shopping-frontend/src/pages/error/ForbiddenPage.tsx
/**
 * 403 Forbidden Page
 * 권한이 없는 경우 표시되는 페이지
 */
import React from 'react'
import { useNavigate } from 'react-router-dom'
import { Button } from '@portal/design-system-react'

export const ForbiddenPage: React.FC = () => {
  const navigate = useNavigate()

  return (
    <div className="min-h-[600px] flex items-center justify-center px-6">
      <div className="text-center max-w-md">
        {/* Icon */}
        <div className="w-20 h-20 mx-auto mb-6 bg-status-error-bg rounded-full flex items-center justify-center">
          <svg
            className="w-10 h-10 text-status-error"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
            />
          </svg>
        </div>

        {/* Title */}
        <h1 className="text-3xl font-bold text-text-heading mb-3">
          Access Denied
        </h1>

        {/* Message */}
        <p className="text-text-body mb-2">
          You don't have permission to access this page.
        </p>
        <p className="text-sm text-text-meta mb-8">
          This area is restricted to administrators only.
        </p>

        {/* Actions */}
        <div className="flex items-center justify-center gap-3">
          <Button
            variant="secondary"
            onClick={() => navigate(-1)}
          >
            Go Back
          </Button>
          <Button
            variant="primary"
            onClick={() => navigate('/')}
          >
            Go to Home
          </Button>
        </div>
      </div>
    </div>
  )
}

export default ForbiddenPage
