// frontend/design-system-vue/src/components/Tabs/Tabs.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import type { TabsProps, TabsEmits, TabItem } from './Tabs.types';

const props = withDefaults(defineProps<TabsProps>(), {
  variant: 'default',
  size: 'md',
  fullWidth: false,
});

const emit = defineEmits<TabsEmits>();

const tablistRef = ref<HTMLDivElement | null>(null);

const sizeClasses = {
  sm: 'text-sm px-3 py-1.5',
  md: 'text-base px-4 py-2',
  lg: 'text-lg px-5 py-2.5',
};

const containerClasses = computed(() => {
  const base = ['flex'];

  if (props.variant === 'default') {
    base.push('border-b border-border-default');
  } else if (props.variant === 'pills') {
    base.push('gap-1 p-1 bg-gray-100 rounded-lg dark:bg-gray-800');
  } else if (props.variant === 'underline') {
    base.push('border-b-2 border-border-default');
  }

  if (props.fullWidth) {
    base.push('w-full');
  }

  return base;
});

const getTabClasses = (tab: TabItem) => {
  const isActive = props.modelValue === tab.value;
  const base = [
    'relative inline-flex items-center justify-center font-medium transition-all duration-200',
    'focus:outline-none focus:ring-2 focus:ring-brand-500/20 focus:ring-offset-2',
    sizeClasses[props.size],
  ];

  if (props.fullWidth) {
    base.push('flex-1');
  }

  if (tab.disabled) {
    base.push('cursor-not-allowed opacity-50');
  } else {
    base.push('cursor-pointer');
  }

  if (props.variant === 'default') {
    base.push(
      isActive
        ? 'text-brand-600 border-b-2 border-brand-600 -mb-px dark:text-brand-400 dark:border-brand-400'
        : 'text-text-muted hover:text-text-body border-b-2 border-transparent -mb-px'
    );
  } else if (props.variant === 'pills') {
    base.push(
      'rounded-md',
      isActive
        ? 'bg-white text-brand-600 shadow-sm dark:bg-gray-700 dark:text-brand-400'
        : 'text-text-muted hover:text-text-body'
    );
  } else if (props.variant === 'underline') {
    base.push(
      isActive
        ? 'text-brand-600 border-b-2 border-brand-600 -mb-0.5 dark:text-brand-400 dark:border-brand-400'
        : 'text-text-muted hover:text-text-body border-b-2 border-transparent -mb-0.5'
    );
  }

  return base;
};

const selectTab = (tab: TabItem) => {
  if (tab.disabled) return;
  emit('update:modelValue', tab.value);
  emit('change', tab.value);
};

const handleKeydown = (event: KeyboardEvent, currentIndex: number) => {
  const enabledTabs = props.items.filter(t => !t.disabled);
  const currentEnabledIndex = enabledTabs.findIndex(t => t.value === props.items[currentIndex].value);

  let newIndex = currentEnabledIndex;

  switch (event.key) {
    case 'ArrowLeft':
      event.preventDefault();
      newIndex = currentEnabledIndex > 0 ? currentEnabledIndex - 1 : enabledTabs.length - 1;
      break;
    case 'ArrowRight':
      event.preventDefault();
      newIndex = currentEnabledIndex < enabledTabs.length - 1 ? currentEnabledIndex + 1 : 0;
      break;
    case 'Home':
      event.preventDefault();
      newIndex = 0;
      break;
    case 'End':
      event.preventDefault();
      newIndex = enabledTabs.length - 1;
      break;
    default:
      return;
  }

  const newTab = enabledTabs[newIndex];
  if (newTab) {
    selectTab(newTab);
    // Focus the new tab
    const tabElements = tablistRef.value?.querySelectorAll('[role="tab"]');
    const newTabIndex = props.items.findIndex(t => t.value === newTab.value);
    (tabElements?.[newTabIndex] as HTMLElement)?.focus();
  }
};
</script>

<template>
  <div ref="tablistRef" role="tablist" :class="containerClasses">
    <button
      v-for="(tab, index) in items"
      :key="tab.value"
      role="tab"
      type="button"
      :aria-selected="modelValue === tab.value"
      :aria-disabled="tab.disabled"
      :tabindex="modelValue === tab.value ? 0 : -1"
      :class="getTabClasses(tab)"
      @click="selectTab(tab)"
      @keydown="handleKeydown($event, index)"
    >
      <slot name="tab" :tab="tab" :active="modelValue === tab.value">
        {{ tab.label }}
      </slot>
    </button>
  </div>
</template>

// frontend/design-react/src/components/Tabs/Tabs.tsx
import { forwardRef, useRef, useCallback, type HTMLAttributes, type KeyboardEvent } from 'react';
import type { TabsProps, TabItem } from '@portal/design-core';
import { cn, tabsBase, tabsVariants, tabsItemBase, tabsItemVariants, tabsSizes } from '@portal/design-core';

export interface TabsComponentProps
  extends Omit<TabsProps, 'value'>,
    Omit<HTMLAttributes<HTMLDivElement>, 'onChange'> {
  value: string;
  onChange?: (value: string) => void;
}

export const Tabs = forwardRef<HTMLDivElement, TabsComponentProps>(
  (
    {
      value,
      items,
      variant = 'underline',
      size = 'md',
      fullWidth = false,
      onChange,
      className,
      ...props
    },
    ref
  ) => {
    const tablistRef = useRef<HTMLDivElement | null>(null);

    const getTabStyles = (isActive: boolean, isDisabled: boolean) => {
      const variantStyles = tabsItemVariants[variant];
      return cn(
        tabsItemBase,
        'focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-primary',
        tabsSizes[size],
        isActive ? variantStyles.active : variantStyles.inactive,
        isDisabled && 'opacity-50 cursor-not-allowed',
        fullWidth && 'flex-1'
      );
    };

    const handleKeyDown = useCallback(
      (e: KeyboardEvent, currentIndex: number) => {
        const enabledTabs = items.filter((t) => !t.disabled);
        const currentEnabledIndex = enabledTabs.findIndex(
          (t) => t.value === items[currentIndex].value
        );

        let newIndex = currentEnabledIndex;

        switch (e.key) {
          case 'ArrowLeft':
            e.preventDefault();
            newIndex = currentEnabledIndex > 0 ? currentEnabledIndex - 1 : enabledTabs.length - 1;
            break;
          case 'ArrowRight':
            e.preventDefault();
            newIndex = currentEnabledIndex < enabledTabs.length - 1 ? currentEnabledIndex + 1 : 0;
            break;
          case 'Home':
            e.preventDefault();
            newIndex = 0;
            break;
          case 'End':
            e.preventDefault();
            newIndex = enabledTabs.length - 1;
            break;
          default:
            return;
        }

        const newTab = enabledTabs[newIndex];
        if (newTab) {
          onChange?.(newTab.value);
          const tabElements = tablistRef.current?.querySelectorAll<HTMLElement>('[role="tab"]');
          const newTabIndex = items.findIndex((t) => t.value === newTab.value);
          tabElements?.[newTabIndex]?.focus();
        }
      },
      [items, onChange]
    );

    return (
      <div
        ref={(node) => {
          tablistRef.current = node;
          if (typeof ref === 'function') ref(node);
          else if (ref) ref.current = node;
        }}
        role="tablist"
        className={cn(
          tabsBase,
          tabsVariants[variant],
          fullWidth && 'w-full',
          className
        )}
        {...props}
      >
        {items.map((item: TabItem, index: number) => (
          <button
            key={item.value}
            type="button"
            role="tab"
            aria-selected={value === item.value}
            aria-disabled={item.disabled}
            tabIndex={value === item.value ? 0 : -1}
            disabled={item.disabled}
            onClick={() => !item.disabled && onChange?.(item.value)}
            onKeyDown={(e) => handleKeyDown(e, index)}
            className={getTabStyles(value === item.value, !!item.disabled)}
          >
            {item.icon && <span className="mr-2">{item.icon}</span>}
            {item.label}
          </button>
        ))}
      </div>
    );
  }
);

Tabs.displayName = 'Tabs';

export default Tabs;
