// frontend/design-react/src/components/Divider/Divider.tsx
import { forwardRef, type HTMLAttributes } from 'react';
import type { DividerProps } from '@portal/design-core';
import { cn, dividerVariants, dividerColors, dividerSpacing } from '@portal/design-core';

export interface DividerComponentProps
  extends DividerProps,
    Omit<HTMLAttributes<HTMLHRElement>, 'color'> {}

export const Divider = forwardRef<HTMLHRElement, DividerComponentProps>(
  (
    {
      orientation = 'horizontal',
      variant = 'solid',
      color = 'default',
      label,
      spacing = 'md',
      className,
      ...props
    },
    ref
  ) => {
    if (label) {
      return (
        <div
          className={cn(
            'flex items-center',
            orientation === 'vertical' ? 'flex-col h-full' : 'w-full',
            dividerSpacing[spacing],
            className
          )}
        >
          <hr
            ref={ref}
            className={cn(
              'flex-1',
              orientation === 'vertical' ? 'border-l h-full w-0' : 'border-t w-full h-0',
              dividerVariants[variant],
              dividerColors[color]
            )}
            {...props}
          />
          <span className="px-3 text-sm text-text-muted">{label}</span>
          <hr
            className={cn(
              'flex-1',
              orientation === 'vertical' ? 'border-l h-full w-0' : 'border-t w-full h-0',
              dividerVariants[variant],
              dividerColors[color]
            )}
          />
        </div>
      );
    }

    return (
      <hr
        ref={ref}
        className={cn(
          orientation === 'vertical'
            ? 'border-l h-full w-0 mx-4'
            : 'border-t w-full h-0',
          dividerVariants[variant],
          dividerColors[color],
          dividerSpacing[spacing],
          className
        )}
        {...props}
      />
    );
  }
);

Divider.displayName = 'Divider';

export default Divider;

// frontend/design-vue/src/components/Divider/Divider.vue
<script setup lang="ts">
import { computed } from 'vue';
import { dividerVariants, dividerColors, dividerSpacing, dividerVerticalSpacing } from '@portal/design-core';
import type { DividerProps } from '@portal/design-core';

const props = withDefaults(defineProps<DividerProps>(), {
  orientation: 'horizontal',
  variant: 'solid',
  color: 'default',
  spacing: 'md',
});

const isHorizontal = computed(() => props.orientation === 'horizontal');
const hasLabel = computed(() => props.label || false);

const dividerClasses = computed(() => {
  if (isHorizontal.value) {
    if (hasLabel.value) {
      return [
        'flex items-center',
        dividerSpacing[props.spacing],
      ];
    }
    return [
      'border-t',
      dividerVariants[props.variant],
      dividerColors[props.color],
      dividerSpacing[props.spacing],
    ];
  }
  return [
    'border-l self-stretch',
    dividerVariants[props.variant],
    dividerColors[props.color],
    dividerVerticalSpacing[props.spacing],
  ];
});

const lineClasses = computed(() => [
  'flex-1 border-t',
  dividerVariants[props.variant],
  dividerColors[props.color],
]);
</script>

<template>
  <div
    :class="dividerClasses"
    :role="label ? 'separator' : undefined"
    :aria-orientation="orientation"
  >
    <template v-if="isHorizontal && hasLabel">
      <div :class="lineClasses" />
      <span class="px-3 text-sm text-text-muted whitespace-nowrap">
        <slot>{{ label }}</slot>
      </span>
      <div :class="lineClasses" />
    </template>
  </div>
</template>
