// frontend/design-react/src/components/Checkbox/Checkbox.tsx
import { forwardRef, type InputHTMLAttributes, useId } from 'react';
import type { CheckboxProps } from '@portal/design-core';
import { cn } from '@portal/design-core';

export interface CheckboxComponentProps
  extends Omit<CheckboxProps, 'checked'>,
    Omit<InputHTMLAttributes<HTMLInputElement>, 'size' | 'type' | 'value'> {
  checked?: boolean;
  value?: string | number;
}

const sizeClasses: Record<NonNullable<CheckboxProps['size']>, { box: string; label: string }> = {
  sm: { box: 'w-4 h-4', label: 'text-sm' },
  md: { box: 'w-5 h-5', label: 'text-base' },
  lg: { box: 'w-6 h-6', label: 'text-lg' },
};

export const Checkbox = forwardRef<HTMLInputElement, CheckboxComponentProps>(
  (
    {
      checked,
      indeterminate,
      disabled,
      label,
      error,
      errorMessage,
      size = 'md',
      id: providedId,
      className,
      ...props
    },
    ref
  ) => {
    const generatedId = useId();
    const id = providedId || generatedId;
    const sizes = sizeClasses[size];

    return (
      <div className={cn('flex flex-col', className)}>
        <label
          htmlFor={id}
          className={cn(
            'inline-flex items-center gap-2 cursor-pointer',
            disabled && 'opacity-50 cursor-not-allowed'
          )}
        >
          <div className="relative flex items-center justify-center">
            <input
              ref={ref}
              type="checkbox"
              id={id}
              checked={checked}
              disabled={disabled}
              aria-invalid={error}
              aria-describedby={error && errorMessage ? `${id}-error` : undefined}
              className={cn(
                'appearance-none rounded border bg-bg-card',
                'transition-all duration-normal ease-linear-ease',
                'focus:outline-none focus:ring-2 focus:ring-brand-primary focus:ring-offset-2',
                'checked:bg-brand-primary checked:border-brand-primary',
                sizes.box,
                error
                  ? 'border-status-error'
                  : 'border-border-default hover:border-border-hover',
                disabled && 'cursor-not-allowed'
              )}
              {...props}
            />
            <svg
              className={cn(
                'absolute pointer-events-none text-white',
                sizes.box,
                'opacity-0 transition-opacity',
                checked && 'opacity-100'
              )}
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={3}
            >
              {indeterminate ? (
                <path strokeLinecap="round" strokeLinejoin="round" d="M5 12h14" />
              ) : (
                <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
              )}
            </svg>
          </div>
          {label && (
            <span className={cn('text-text-body', sizes.label)}>{label}</span>
          )}
        </label>
        {error && errorMessage && (
          <p id={`${id}-error`} className="mt-1 text-sm text-status-error ml-7">
            {errorMessage}
          </p>
        )}
      </div>
    );
  }
);

Checkbox.displayName = 'Checkbox';

export default Checkbox;

// frontend/design-vue/src/components/Checkbox/Checkbox.vue
<script setup lang="ts">
import { computed, ref, watch, onMounted } from 'vue';
import type { CheckboxProps, CheckboxEmits } from './Checkbox.types';

const props = withDefaults(defineProps<CheckboxProps>(), {
  modelValue: false,
  indeterminate: false,
  disabled: false,
  error: false,
  size: 'md',
});

const emit = defineEmits<CheckboxEmits>();

const inputRef = ref<HTMLInputElement | null>(null);
const uniqueId = computed(() => props.id || `checkbox-${Math.random().toString(36).substr(2, 9)}`);
const errorId = computed(() => props.errorMessage ? `${uniqueId.value}-error` : undefined);

const sizeClasses = {
  sm: {
    box: 'w-4 h-4',
    label: 'text-sm',
    icon: 'w-3 h-3',
  },
  md: {
    box: 'w-5 h-5',
    label: 'text-base',
    icon: 'w-3.5 h-3.5',
  },
  lg: {
    box: 'w-6 h-6',
    label: 'text-lg',
    icon: 'w-4 h-4',
  },
};

const boxClasses = computed(() => [
  'relative flex items-center justify-center rounded border-2 transition-all duration-200',
  sizeClasses[props.size].box,
  props.disabled
    ? 'bg-bg-disabled border-border-muted cursor-not-allowed'
    : props.error
      ? 'border-status-error focus-within:ring-2 focus-within:ring-status-error/20'
      : props.modelValue || props.indeterminate
        ? 'bg-brand-primary border-brand-primary'
        : 'border-border-default hover:border-brand-primary focus-within:ring-2 focus-within:ring-brand-primary/20',
]);

const handleChange = (event: Event) => {
  if (props.disabled) return;
  const target = event.target as HTMLInputElement;
  emit('update:modelValue', target.checked);
  emit('change', target.checked);
};

watch(
  () => props.indeterminate,
  (value) => {
    if (inputRef.value) {
      inputRef.value.indeterminate = value;
    }
  }
);

onMounted(() => {
  if (inputRef.value && props.indeterminate) {
    inputRef.value.indeterminate = true;
  }
});
</script>

<template>
  <div class="inline-flex flex-col">
    <label
      :for="uniqueId"
      :class="[
        'inline-flex items-center gap-2 cursor-pointer',
        disabled && 'cursor-not-allowed opacity-60',
      ]"
    >
      <span :class="boxClasses">
        <input
          :id="uniqueId"
          ref="inputRef"
          type="checkbox"
          :checked="modelValue"
          :disabled="disabled"
          :name="name"
          :value="value"
          :aria-checked="indeterminate ? 'mixed' : modelValue"
          :aria-describedby="errorId"
          :aria-invalid="error"
          class="absolute inset-0 opacity-0 cursor-pointer disabled:cursor-not-allowed"
          @change="handleChange"
        />
        <!-- Check icon -->
        <svg
          v-if="modelValue && !indeterminate"
          :class="['text-white', sizeClasses[size].icon]"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          stroke-width="3"
        >
          <path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
        </svg>
        <!-- Indeterminate icon -->
        <svg
          v-if="indeterminate"
          :class="['text-white', sizeClasses[size].icon]"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          stroke-width="3"
        >
          <path stroke-linecap="round" stroke-linejoin="round" d="M5 12h14" />
        </svg>
      </span>
      <span
        v-if="label"
        :class="[
          'text-text-body select-none',
          sizeClasses[size].label,
        ]"
      >
        {{ label }}
      </span>
      <slot />
    </label>
    <p
      v-if="error && errorMessage"
      :id="errorId"
      class="mt-1 text-sm text-status-error"
    >
      {{ errorMessage }}
    </p>
  </div>
</template>
