// frontend/design-system-react/src/components/Alert/Alert.tsx
import { forwardRef, useState, type HTMLAttributes, type ReactNode } from 'react';
import type { AlertProps } from '@portal/design-types';
import { cn } from '../../utils/cn';

export interface AlertComponentProps
  extends AlertProps,
    Omit<HTMLAttributes<HTMLDivElement>, 'title'> {
  children?: ReactNode;
  onDismiss?: () => void;
}

const variantClasses: Record<
  NonNullable<AlertProps['variant']>,
  { container: string; icon: string }
> = {
  info: {
    container: 'bg-status-infoBg border-status-info/30 text-text-body',
    icon: 'text-status-info',
  },
  success: {
    container: 'bg-status-successBg border-status-success/30 text-text-body',
    icon: 'text-status-success',
  },
  warning: {
    container: 'bg-status-warningBg border-status-warning/30 text-text-body',
    icon: 'text-status-warning',
  },
  error: {
    container: 'bg-status-errorBg border-status-error/30 text-text-body',
    icon: 'text-status-error',
  },
};

const icons: Record<NonNullable<AlertProps['variant']>, ReactNode> = {
  info: (
    <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={2}
        d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
      />
    </svg>
  ),
  success: (
    <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={2}
        d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
      />
    </svg>
  ),
  warning: (
    <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={2}
        d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
      />
    </svg>
  ),
  error: (
    <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={2}
        d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"
      />
    </svg>
  ),
};

export const Alert = forwardRef<HTMLDivElement, AlertComponentProps>(
  (
    {
      variant = 'info',
      title,
      dismissible = false,
      showIcon = true,
      bordered = false,
      className,
      children,
      onDismiss,
      ...props
    },
    ref
  ) => {
    const [dismissed, setDismissed] = useState(false);

    if (dismissed) return null;

    const handleDismiss = () => {
      setDismissed(true);
      onDismiss?.();
    };

    const styles = variantClasses[variant];

    return (
      <div
        ref={ref}
        role="alert"
        className={cn(
          'flex gap-3 p-4 rounded-lg',
          styles.container,
          bordered && 'border',
          className
        )}
        {...props}
      >
        {showIcon && <div className={cn('shrink-0', styles.icon)}>{icons[variant]}</div>}
        <div className="flex-1 min-w-0">
          {title && (
            <h5 className="font-medium text-text-heading mb-1">{title}</h5>
          )}
          <div className="text-sm">{children}</div>
        </div>
        {dismissible && (
          <button
            type="button"
            onClick={handleDismiss}
            className={cn(
              'shrink-0 p-1 rounded-md hover:bg-black/10',
              'transition-colors duration-fast',
              'focus:outline-none focus:ring-2 focus:ring-brand-primary'
            )}
            aria-label="Dismiss"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        )}
      </div>
    );
  }
);

Alert.displayName = 'Alert';

export default Alert;

// frontend/design-vue/src/components/Alert/Alert.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { alertBase, alertVariants } from '@portal/design-core';
import type { AlertProps, AlertEmits } from './Alert.types';

const props = withDefaults(defineProps<AlertProps>(), {
  variant: 'info',
  dismissible: false,
  showIcon: true,
  bordered: false,
});

const emit = defineEmits<AlertEmits>();

const isVisible = ref(true);

const containerClasses = computed(() => [
  alertBase,
  alertVariants[props.variant].container,
  props.bordered && 'border',
]);

const dismiss = () => {
  isVisible.value = false;
  emit('dismiss');
};
</script>

<template>
  <Transition
    enter-active-class="transition duration-200 ease-out"
    enter-from-class="transform scale-95 opacity-0"
    enter-to-class="transform scale-100 opacity-100"
    leave-active-class="transition duration-150 ease-in"
    leave-from-class="transform scale-100 opacity-100"
    leave-to-class="transform scale-95 opacity-0"
  >
    <div
      v-if="isVisible"
      role="alert"
      aria-live="polite"
      :class="containerClasses"
    >
      <!-- Icon -->
      <div v-if="showIcon" :class="['flex-shrink-0', alertVariants[variant].icon]">
        <slot name="icon">
          <!-- Info icon -->
          <svg v-if="variant === 'info'" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd" />
          </svg>
          <!-- Success icon -->
          <svg v-else-if="variant === 'success'" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
          </svg>
          <!-- Warning icon -->
          <svg v-else-if="variant === 'warning'" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
          </svg>
          <!-- Error icon -->
          <svg v-else-if="variant === 'error'" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
          </svg>
        </slot>
      </div>

      <!-- Content -->
      <div class="flex-1 min-w-0">
        <h3 v-if="title" class="font-semibold mb-1">
          {{ title }}
        </h3>
        <div class="text-sm">
          <slot />
        </div>
        <div v-if="$slots.action" class="mt-3">
          <slot name="action" />
        </div>
      </div>

      <!-- Dismiss button -->
      <button
        v-if="dismissible"
        type="button"
        class="flex-shrink-0 p-1 -m-1 rounded hover:bg-black/10 dark:hover:bg-white/10 transition-colors"
        aria-label="Dismiss"
        @click="dismiss"
      >
        <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
          <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
        </svg>
      </button>
    </div>
  </Transition>
</template>
