// frontend/drive-frontend/src/App.vue
<script setup lang="ts">
import { computed, watch, onMounted, onActivated } from 'vue';
import { useRoute } from 'vue-router';

const route = useRoute();
const isEmbedded = computed(() => window.__POWERED_BY_PORTAL_SHELL__ === true);

function updateDataTheme() {
  const isDark = document.documentElement.classList.contains('dark');
  document.documentElement.setAttribute('data-theme', isDark ? 'dark' : 'light');
}

onMounted(() => {
  document.documentElement.setAttribute('data-service', 'drive');
  updateDataTheme();

  if (isEmbedded.value) {
    import('portal/stores').then(({ useThemeStore }) => {
      const store = useThemeStore();

      if (store.isDark) {
        document.documentElement.classList.add('dark');
      } else {
        document.documentElement.classList.remove('dark');
      }
      updateDataTheme();

      watch(() => store.isDark, (newVal) => {
        if (newVal) {
          document.documentElement.classList.add('dark');
        } else {
          document.documentElement.classList.remove('dark');
        }
        updateDataTheme();
      });
    }).catch(() => {
      // Portal Shell themeStore load failed - ignore
    });
  } else {
    const observer = new MutationObserver((mutations) => {
      mutations.forEach((mutation) => {
        if (mutation.attributeName === 'class') {
          updateDataTheme();
        }
      });
    });

    observer.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ['class']
    });
  }
});

onActivated(() => {
  document.documentElement.setAttribute('data-service', 'drive');
  updateDataTheme();
});
</script>

<template>
  <div class="min-h-screen bg-bg-page">
    <!-- Header (Standalone only) -->
    <header
        v-if="!isEmbedded"
        class="bg-bg-card border-b border-border-default sticky top-0 z-50"
    >
      <div class="max-w-7xl mx-auto px-4 py-4">
        <div class="flex items-center justify-between">
          <router-link to="/" class="flex items-center gap-3 hover:opacity-80 transition-opacity">
            <div class="w-10 h-10 rounded-lg bg-gradient-to-br from-brand-primary to-brand-secondary flex items-center justify-center shadow-lg">
              <span class="text-white font-bold text-lg">D</span>
            </div>
            <span class="text-xl font-bold text-text-heading">Drive</span>
          </router-link>

          <div class="px-3 py-1 bg-status-success-bg text-status-success text-sm font-medium rounded-full border border-status-success/20">
            Standalone
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <main :class="isEmbedded ? 'py-4' : 'py-8'">
      <router-view v-slot="{ Component }">
        <component :is="Component" v-if="Component" />

        <div v-else class="max-w-5xl mx-auto px-6">
          <div class="bg-status-error-bg border border-status-error/20 rounded-lg p-8 text-center">
            <p class="text-xl text-status-error mb-4">
              Page not found: {{ route.path }}
            </p>
            <button
              class="px-4 py-2 bg-brand-primary text-white rounded-lg"
              @click="$router.push('/')"
            >
              Go Home
            </button>
          </div>
        </div>
      </router-view>
    </main>

    <!-- Footer (Standalone only) -->
    <footer
        v-if="!isEmbedded"
        class="bg-bg-card border-t border-border-default mt-auto"
    >
      <div class="max-w-7xl mx-auto px-4 py-6 text-center">
        <p class="text-sm text-text-meta">
          Portal Universe Drive
        </p>
      </div>
    </footer>
  </div>
</template>

// frontend/shopping-seller-frontend/src/App.tsx
import { useEffect } from 'react'
import { SellerRouter } from '@/router'
import { usePortalTheme } from '@portal/react-bridge'
import { ToastContainer, useToast, ErrorBoundary } from '@portal/design-react'
import './styles/index.css'

interface AppProps {
  theme?: 'light' | 'dark'
  locale?: string
  userRole?: 'guest' | 'user' | 'admin'
  initialPath?: string
  onNavigate?: (path: string) => void
}

function App({
  theme = 'light',
  locale: _locale = 'ko',
  userRole: _userRole = 'guest',
  initialPath = '/',
  onNavigate,
}: AppProps) {
  const { toasts, removeToast } = useToast()
  const isEmbedded = window.__POWERED_BY_PORTAL_SHELL__ === true
  const portalTheme = usePortalTheme()

  const isDark = isEmbedded && portalTheme.isConnected
    ? portalTheme.isDark
    : theme === 'dark'

  const updateDataTheme = (isDark: boolean) => {
    const themeValue = isDark ? 'dark' : 'light'
    document.documentElement.setAttribute('data-theme', themeValue)
  }

  useEffect(() => {
    if (isDark) {
      document.documentElement.classList.add('dark')
    } else {
      document.documentElement.classList.remove('dark')
    }
    updateDataTheme(isDark)
  }, [isDark, isEmbedded, portalTheme.isConnected])

  useEffect(() => {
    document.documentElement.setAttribute('data-service', 'shopping')
  }, [])

  return (
    <ErrorBoundary moduleName="ShoppingSeller">
      <div className="min-h-screen bg-bg-page">
        <ToastContainer toasts={toasts} onDismiss={removeToast} />
        {!isEmbedded && (
          <header className="bg-bg-card border-b border-border-default sticky top-0 z-50">
            <div className="max-w-7xl mx-auto px-4 py-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-brand-primary to-brand-secondary flex items-center justify-center shadow-lg">
                    <span className="text-white font-bold text-lg">S</span>
                  </div>
                  <span className="text-xl font-bold text-text-heading">Seller Portal</span>
                </div>
                <div className="px-3 py-1 bg-status-success-bg text-status-success text-sm font-medium rounded-full border border-status-success/20">
                  Standalone
                </div>
              </div>
            </div>
          </header>
        )}
        <main className={isEmbedded ? '' : ''}>
          <SellerRouter
            isEmbedded={isEmbedded}
            initialPath={initialPath}
            onNavigate={onNavigate}
          />
        </main>
      </div>
    </ErrorBoundary>
  )
}

export default App
