// frontend/design-vue/src/components/Progress/Progress.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { ProgressProps } from '@portal/design-core';

const props = withDefaults(defineProps<ProgressProps>(), {
  max: 100,
  size: 'md',
  showLabel: false,
  variant: 'default',
});

const percentage = computed(() => {
  const raw = (props.value / props.max) * 100;
  return Math.min(100, Math.max(0, raw));
});

const sizeClasses: Record<string, string> = {
  sm: 'h-1',
  md: 'h-2',
  lg: 'h-3',
};

const variantClasses: Record<string, string> = {
  default: 'bg-brand-primary',
  info: 'bg-status-info',
  success: 'bg-status-success',
  warning: 'bg-status-warning',
  error: 'bg-status-error',
};
</script>

<template>
  <div class="w-full">
    <div class="flex items-center gap-2">
      <div
        role="progressbar"
        :aria-valuenow="value"
        :aria-valuemin="0"
        :aria-valuemax="max"
        :class="['w-full rounded-full bg-bg-muted overflow-hidden', sizeClasses[size]]"
      >
        <div
          :class="['h-full rounded-full transition-all duration-300', variantClasses[variant]]"
          :style="{ width: `${percentage}%` }"
        />
      </div>
      <span v-if="showLabel" class="text-sm text-text-meta whitespace-nowrap">
        {{ Math.round(percentage) }}%
      </span>
    </div>
  </div>
</template>

// frontend/design-system-react/src/components/Progress/Progress.tsx
import { forwardRef, type HTMLAttributes } from 'react';
import type { ProgressProps } from '@portal/design-types';
import { cn } from '../../utils/cn';

export interface ProgressComponentProps
  extends ProgressProps,
    HTMLAttributes<HTMLDivElement> {}

const sizeClasses: Record<NonNullable<ProgressProps['size']>, string> = {
  sm: 'h-1',
  md: 'h-2',
  lg: 'h-3',
};

const variantClasses: Record<NonNullable<ProgressProps['variant']>, string> = {
  default: 'bg-brand-primary',
  info: 'bg-status-info',
  success: 'bg-status-success',
  warning: 'bg-status-warning',
  error: 'bg-status-error',
};

export const Progress = forwardRef<HTMLDivElement, ProgressComponentProps>(
  (
    {
      value,
      max = 100,
      size = 'md',
      showLabel = false,
      variant = 'default',
      className,
      ...props
    },
    ref
  ) => {
    const percentage = Math.min(Math.max((value / max) * 100, 0), 100);

    return (
      <div ref={ref} className={cn('w-full', className)} {...props}>
        <div
          className={cn(
            'w-full rounded-full bg-bg-muted overflow-hidden',
            sizeClasses[size]
          )}
          role="progressbar"
          aria-valuenow={value}
          aria-valuemin={0}
          aria-valuemax={max}
        >
          <div
            className={cn(
              'h-full rounded-full transition-all duration-normal ease-linear-ease',
              variantClasses[variant]
            )}
            style={{ width: `${percentage}%` }}
          />
        </div>
        {showLabel && (
          <div className="mt-1 text-sm text-text-muted text-right">
            {Math.round(percentage)}%
          </div>
        )}
      </div>
    );
  }
);

Progress.displayName = 'Progress';

export default Progress;
