// frontend/design-vue/src/components/Spinner/Spinner.vue
<script setup lang="ts">
import { computed } from 'vue';
import { spinnerSizes } from '@portal/design-core';
import type { SpinnerProps } from '@portal/design-core';

const props = withDefaults(defineProps<SpinnerProps>(), {
  size: 'md',
  color: 'primary',
  label: 'Loading',
});

// Vue uses border-based spinner (different from React SVG-based)
// Keep colorClasses local as they differ between Vue and React implementations
const colorClasses = {
  primary: 'border-brand-600 border-t-transparent dark:border-brand-400',
  current: 'border-current border-t-transparent',
  white: 'border-white border-t-transparent',
};

const spinnerClasses = computed(() => [
  'inline-block rounded-full animate-spin',
  spinnerSizes[props.size],
  colorClasses[props.color],
]);
</script>

<template>
  <div
    role="status"
    :aria-label="label"
    :class="spinnerClasses"
  >
    <span class="sr-only">{{ label }}</span>
  </div>
</template>

<style scoped>
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border-width: 0;
}

.border-3 {
  border-width: 3px;
}
</style>

// frontend/design-system-react/src/components/Spinner/Spinner.tsx
import { forwardRef, type HTMLAttributes } from 'react';
import type { SpinnerProps } from '@portal/design-types';
import { cn } from '../../utils/cn';

export interface SpinnerComponentProps
  extends SpinnerProps,
    Omit<HTMLAttributes<HTMLDivElement>, 'color'> {}

const sizeClasses: Record<NonNullable<SpinnerProps['size']>, string> = {
  xs: 'w-3 h-3',
  sm: 'w-4 h-4',
  md: 'w-6 h-6',
  lg: 'w-8 h-8',
  xl: 'w-12 h-12',
};

const colorClasses: Record<NonNullable<SpinnerProps['color']>, string> = {
  primary: 'text-brand-primary',
  current: 'text-current',
  white: 'text-white',
};

export const Spinner = forwardRef<HTMLDivElement, SpinnerComponentProps>(
  ({ size = 'md', color = 'primary', label = 'Loading', className, ...props }, ref) => {
    return (
      <div
        ref={ref}
        role="status"
        aria-label={label}
        className={cn('inline-flex', className)}
        {...props}
      >
        <svg
          className={cn('animate-spin', sizeClasses[size], colorClasses[color])}
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
        >
          <circle
            className="opacity-25"
            cx="12"
            cy="12"
            r="10"
            stroke="currentColor"
            strokeWidth="4"
          />
          <path
            className="opacity-75"
            fill="currentColor"
            d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
          />
        </svg>
        <span className="sr-only">{label}</span>
      </div>
    );
  }
);

Spinner.displayName = 'Spinner';

export default Spinner;
