// frontend/design-vue/src/components/Radio/Radio.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { RadioProps, RadioEmits } from './Radio.types';

const props = withDefaults(defineProps<RadioProps>(), {
  direction: 'vertical',
  disabled: false,
  error: false,
  size: 'md',
});

const emit = defineEmits<RadioEmits>();

const groupId = computed(() => `radio-group-${Math.random().toString(36).substr(2, 9)}`);
const errorId = computed(() => props.errorMessage ? `${groupId.value}-error` : undefined);

const sizeClasses = {
  sm: {
    radio: 'w-4 h-4',
    dot: 'w-1.5 h-1.5',
    label: 'text-sm',
    gap: 'gap-2',
  },
  md: {
    radio: 'w-5 h-5',
    dot: 'w-2 h-2',
    label: 'text-base',
    gap: 'gap-3',
  },
  lg: {
    radio: 'w-6 h-6',
    dot: 'w-2.5 h-2.5',
    label: 'text-lg',
    gap: 'gap-3',
  },
};

const containerClasses = computed(() => [
  'flex',
  props.direction === 'horizontal' ? 'flex-row flex-wrap gap-4' : 'flex-col gap-2',
]);

const getRadioClasses = (option: RadioProps['options'][0]) => {
  const isSelected = props.modelValue === option.value;
  const isDisabled = props.disabled || option.disabled;

  return [
    'relative flex items-center justify-center rounded-full border-2 transition-all duration-200',
    sizeClasses[props.size].radio,
    isDisabled
      ? 'bg-bg-disabled border-border-muted cursor-not-allowed'
      : props.error
        ? 'border-status-error focus-within:ring-2 focus-within:ring-status-error/20'
        : isSelected
          ? 'border-brand-primary'
          : 'border-border-default hover:border-brand-primary focus-within:ring-2 focus-within:ring-brand-primary/20',
  ];
};

const getDotClasses = (option: RadioProps['options'][0]) => {
  const isSelected = props.modelValue === option.value;
  const isDisabled = props.disabled || option.disabled;

  return [
    'rounded-full transition-all duration-200',
    sizeClasses[props.size].dot,
    isSelected
      ? isDisabled
        ? 'bg-text-muted'
        : 'bg-brand-primary'
      : 'bg-transparent',
  ];
};

const handleChange = (value: string | number) => {
  emit('update:modelValue', value);
  emit('change', value);
};
</script>

<template>
  <div
    role="radiogroup"
    :aria-describedby="errorId"
    :aria-invalid="error"
  >
    <div :class="containerClasses">
      <label
        v-for="option in options"
        :key="String(option.value)"
        :class="[
          'inline-flex items-center cursor-pointer',
          sizeClasses[size].gap,
          (disabled || option.disabled) && 'cursor-not-allowed opacity-60',
        ]"
      >
        <span :class="getRadioClasses(option)">
          <input
            type="radio"
            :name="name"
            :value="option.value"
            :checked="modelValue === option.value"
            :disabled="disabled || option.disabled"
            class="absolute inset-0 opacity-0 cursor-pointer disabled:cursor-not-allowed"
            @change="handleChange(option.value)"
          />
          <span :class="getDotClasses(option)" />
        </span>
        <span
          :class="[
            'text-text-body select-none',
            sizeClasses[size].label,
          ]"
        >
          {{ option.label }}
        </span>
      </label>
    </div>
    <p
      v-if="error && errorMessage"
      :id="errorId"
      class="mt-2 text-sm text-status-error"
    >
      {{ errorMessage }}
    </p>
  </div>
</template>

// frontend/design-system-react/src/components/Radio/Radio.tsx
import { forwardRef, type InputHTMLAttributes, useId } from 'react';
import type { RadioProps, RadioOption } from '@portal/design-types';
import { cn } from '../../utils/cn';

export interface RadioComponentProps
  extends Omit<RadioProps, 'value' | 'onChange'>,
    Omit<InputHTMLAttributes<HTMLInputElement>, 'size' | 'type' | 'name' | 'onChange'> {
  value?: string | number;
  onChange?: (value: string | number) => void;
}

const sizeClasses: Record<NonNullable<RadioProps['size']>, { radio: string; label: string }> = {
  sm: { radio: 'w-4 h-4', label: 'text-sm' },
  md: { radio: 'w-5 h-5', label: 'text-base' },
  lg: { radio: 'w-6 h-6', label: 'text-lg' },
};

export const Radio = forwardRef<HTMLInputElement, RadioComponentProps>(
  (
    {
      value,
      options,
      name,
      direction = 'vertical',
      disabled,
      error,
      errorMessage,
      size = 'md',
      onChange,
      className,
      ...props
    },
    ref
  ) => {
    const groupId = useId();
    const sizes = sizeClasses[size];

    const handleChange = (optionValue: string | number) => {
      if (onChange) {
        onChange(optionValue);
      }
    };

    return (
      <div
        role="radiogroup"
        aria-invalid={error}
        aria-describedby={error && errorMessage ? `${groupId}-error` : undefined}
        className={cn(
          'flex',
          direction === 'vertical' ? 'flex-col gap-2' : 'flex-row gap-4 flex-wrap',
          className
        )}
      >
        {options.map((option: RadioOption) => {
          const optionId = `${groupId}-${option.value}`;
          const isDisabled = disabled || option.disabled;
          const isChecked = value === option.value;

          return (
            <label
              key={option.value}
              htmlFor={optionId}
              className={cn(
                'inline-flex items-center gap-2 cursor-pointer',
                isDisabled && 'opacity-50 cursor-not-allowed'
              )}
            >
              <div className="relative flex items-center justify-center">
                <input
                  ref={isChecked ? ref : undefined}
                  type="radio"
                  id={optionId}
                  name={name}
                  value={option.value}
                  checked={isChecked}
                  disabled={isDisabled}
                  onChange={() => handleChange(option.value)}
                  className={cn(
                    'appearance-none rounded-full border bg-bg-card',
                    'transition-all duration-normal ease-linear-ease',
                    'focus:outline-none focus:ring-2 focus:ring-brand-primary focus:ring-offset-2',
                    'checked:border-brand-primary',
                    sizes.radio,
                    error
                      ? 'border-status-error'
                      : 'border-border-default hover:border-border-hover',
                    isDisabled && 'cursor-not-allowed'
                  )}
                  {...props}
                />
                <div
                  className={cn(
                    'absolute rounded-full bg-brand-primary',
                    'transition-transform duration-normal ease-linear-ease',
                    'scale-0',
                    isChecked && 'scale-100',
                    size === 'sm' && 'w-2 h-2',
                    size === 'md' && 'w-2.5 h-2.5',
                    size === 'lg' && 'w-3 h-3'
                  )}
                />
              </div>
              <span className={cn('text-text-body', sizes.label)}>{option.label}</span>
            </label>
          );
        })}
        {error && errorMessage && (
          <p id={`${groupId}-error`} className="text-sm text-status-error">
            {errorMessage}
          </p>
        )}
      </div>
    );
  }
);

Radio.displayName = 'Radio';

export default Radio;
