// frontend/prism-frontend/src/App.tsx
/**
 * Prism Frontend - AI Agent Orchestration App
 *
 * Portal Shell과 연동되는 Module Federation Remote 앱
 * Shopping Frontend와 동일한 패턴으로 구현
 */
import { useEffect } from 'react';
import { PrismRouter } from '@/router';
import { useAuthStore } from '@/stores/authStore';
import { usePortalTheme } from '@/hooks/usePortalStore';

declare global {
  interface Window {
    __POWERED_BY_PORTAL_SHELL__?: boolean;
  }
}

/**
 * App Props 인터페이스
 * Portal Shell(Host)에서 전달받는 Props
 */
interface AppProps {
  /** 테마 설정 */
  theme?: 'light' | 'dark';
  /** 언어/로케일 설정 */
  locale?: string;
  /** 사용자 역할 */
  userRole?: 'guest' | 'user' | 'admin';
  /** 초기 라우트 경로 */
  initialPath?: string;
  /** 라우트 변경 콜백 (Parent에게 알림) */
  onNavigate?: (path: string) => void;
  /** 기타 Props */
  [key: string]: any;
}

/**
 * Prism Frontend 루트 컴포넌트
 *
 * 특징:
 * - Portal Shell과 Props 기반으로 통신
 * - data-service="prism" CSS 활성화
 * - data-theme 속성으로 테마 동기화
 * - Portal Shell의 themeStore와 연동 (Embedded 모드)
 */
function App({
  theme = 'light',
  locale = 'ko',
  userRole = 'guest',
  initialPath = '/',
  onNavigate,
  ...otherProps
}: AppProps) {
  // ============================================
  // State 정의
  // ============================================

  /** Portal Shell과의 연동 여부 */
  const isEmbedded = window.__POWERED_BY_PORTAL_SHELL__ === true;

  /** Portal Shell 테마 상태 (Embedded 모드에서 사용) */
  const portalTheme = usePortalTheme();

  /**
   * 현재 적용할 테마 결정
   * - Embedded 모드 & adapter 연결됨: Portal adapter의 isDark 사용
   * - 그 외: props.theme 사용
   */
  const isDark = isEmbedded && portalTheme.isConnected
    ? portalTheme.isDark
    : theme === 'dark';

  // ============================================
  // Helper 함수
  // ============================================

  /**
   * data-theme 속성 동기화
   */
  const updateDataTheme = (isDark: boolean) => {
    const themeValue = isDark ? 'dark' : 'light';
    document.documentElement.setAttribute('data-theme', themeValue);
    console.log(`[Prism] Theme synced: data-theme="${themeValue}"`);
  };

  // ============================================
  // 생명주기 훅
  // ============================================

  /**
   * 테마 변경 감지 및 적용
   */
  useEffect(() => {
    if (isDark) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
    updateDataTheme(isDark);
    console.log(`[Prism] Theme applied: ${isDark ? 'dark' : 'light'} (source: ${
      isEmbedded && portalTheme.isConnected ? 'Portal adapter' : 'props'
    })`);
  }, [isDark, isEmbedded, portalTheme.isConnected]);

  /**
   * 마운트 및 초기 설정
   */
  useEffect(() => {
    console.group('🔧 [Prism] App mounted with props:');
    console.log('  theme:', theme);
    console.log('  locale:', locale);
    console.log('  userRole:', userRole);
    console.log('  isEmbedded:', isEmbedded);
    console.log('  portalTheme.isConnected:', portalTheme.isConnected);
    console.groupEnd();

    // ✅ Step 1: data-service="prism" 속성 설정 (CSS 선택자 활성화)
    document.documentElement.setAttribute('data-service', 'prism');

    if (isEmbedded) {
      // ============================================
      // Embedded 모드: Portal Shell의 authStore 동기화
      // themeStore는 usePortalTheme hook이 자동으로 구독
      // ============================================
      console.log('[Prism] Embedded mode - syncing authStore...');

      const authStore = useAuthStore.getState();
      authStore.syncFromPortal().then(() => {
        console.log('[Prism] Portal Shell authStore synced');
      }).catch((err) => {
        console.warn('[Prism] Failed to sync authStore:', err);
      });
    }
  }, [theme, locale, userRole, isEmbedded, portalTheme.isConnected]);

  // ============================================
  // 렌더링
  // ============================================

  return (
    <div className="min-h-screen bg-bg-page">
      {/* Header (Standalone 모드에서만 표시) */}
      {!isEmbedded && (
        <header className="bg-bg-card border-b border-border-default sticky top-0 z-50">
          <div className="max-w-7xl mx-auto px-4 py-4">
            <div className="flex items-center justify-between">
              {/* Logo */}
              <div className="flex items-center gap-3 hover:opacity-80 transition-opacity cursor-pointer">
                <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-prism-500 to-prism-700 flex items-center justify-center shadow-lg">
                  <span className="text-white font-bold text-lg">P</span>
                </div>
                <span className="text-xl font-bold text-text-heading">Prism</span>
              </div>

              {/* Nav */}
              <nav className="flex items-center gap-6">
                <a
                  href="/"
                  className="text-text-body hover:text-prism-500 font-medium transition-colors"
                >
                  Boards
                </a>
                <a
                  href="/agents"
                  className="text-text-body hover:text-prism-500 font-medium transition-colors"
                >
                  Agents
                </a>
                <a
                  href="/providers"
                  className="text-text-body hover:text-prism-500 font-medium transition-colors"
                >
                  Providers
                </a>
              </nav>

              {/* Mode Badge (Standalone) */}
              <div className="px-3 py-1 bg-status-success-bg text-status-success text-sm font-medium rounded-full border border-status-success/20">
                Standalone
              </div>
            </div>
          </div>
        </header>
      )}

      {/* Main Content */}
      <main className={isEmbedded ? 'py-4' : 'py-8'}>
        <div className="max-w-7xl mx-auto px-6">
          <PrismRouter
            isEmbedded={isEmbedded}
            initialPath={initialPath}
            onNavigate={onNavigate}
          />
        </div>
      </main>

      {/* Footer (Standalone 모드에서만) */}
      {!isEmbedded && (
        <footer className="bg-bg-card border-t border-border-default mt-auto">
          <div className="max-w-7xl mx-auto px-4 py-6 text-center">
            <p className="text-sm text-text-meta">
              © 2025 Portal Universe Prism. All rights reserved.
            </p>
          </div>
        </footer>
      )}
    </div>
  );
}

export default App;

// frontend/blog-frontend/src/App.vue
<script setup lang="ts">
import { computed, watch, onMounted } from 'vue';
import { useRoute } from 'vue-router';
import { Button } from '@portal/design-system';

const route = useRoute();
const isEmbedded = computed(() => window.__POWERED_BY_PORTAL_SHELL__ === true);

// 다크모드 감지
let themeStore: any = null;

/**
 * data-theme 속성 동기화
 * - <html class="dark"> → <html data-theme="dark">
 * - [data-theme="dark"] CSS 선택자 활성화
 */
function updateDataTheme() {
  const isDark = document.documentElement.classList.contains('dark');
  document.documentElement.setAttribute('data-theme', isDark ? 'dark' : 'light');
  console.log(`[Blog] Theme updated: ${isDark ? 'dark' : 'light'}`);
}

onMounted(() => {
  // 초기 data-theme 설정
  updateDataTheme();

  if (isEmbedded.value) {
    // ============================================
    // Embedded 모드: Portal Shell의 themeStore 연동
    // ============================================
    try {
      import('portal_shell/themeStore').then(({ useThemeStore }) => {
        themeStore = useThemeStore();

        // 초기 다크모드 적용
        if (themeStore.isDark) {
          document.documentElement.classList.add('dark');
        } else {
          document.documentElement.classList.remove('dark');
        }
        updateDataTheme();

        // 다크모드 변경 감지
        watch(() => themeStore.isDark, (newVal) => {
          if (newVal) {
            document.documentElement.classList.add('dark');
          } else {
            document.documentElement.classList.remove('dark');
          }
          updateDataTheme();
        });

        console.log('[Blog] Portal Shell themeStore connected');
      }).catch((err) => {
        console.warn('[Blog] Failed to load portal_shell themeStore:', err);
      });
    } catch (err) {
      console.warn('[Blog] themeStore import failed:', err);
    }
  } else {
    // ============================================
    // Standalone 모드: MutationObserver로 dark 클래스 감지
    // ============================================
    const observer = new MutationObserver((mutations) => {
      mutations.forEach((mutation) => {
        if (mutation.attributeName === 'class') {
          updateDataTheme();
        }
      });
    });

    observer.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ['class']
    });

    console.log('[Blog] Standalone mode: MutationObserver registered');
  }
});
</script>

<template>
  <!-- ✅ data-service="blog" 추가 -->
  <!-- ✅ Semantic Classes 사용 (bg-bg-page) -->
  <div data-service="blog" class="min-h-screen bg-bg-page">

    <!-- Header (Standalone 모드에서만 표시) -->
    <header
        v-if="!isEmbedded"
        class="bg-bg-card border-b border-border-default sticky top-0 z-50"
    >
      <div class="max-w-7xl mx-auto px-4 py-4">
        <div class="flex items-center justify-between">
          <!-- Logo -->
          <router-link to="/" class="flex items-center gap-3 hover:opacity-80 transition-opacity">
            <div class="w-10 h-10 rounded-lg bg-gradient-to-br from-brand-primary to-brand-secondary flex items-center justify-center shadow-lg">
              <span class="text-white font-bold text-lg">B</span>
            </div>
            <span class="text-xl font-bold text-text-heading">Blog</span>
          </router-link>

          <!-- Nav -->
          <nav class="flex items-center gap-6">
            <router-link
                to="/"
                class="text-text-body hover:text-brand-primary font-medium transition-colors"
                active-class="text-brand-primary font-bold"
            >
              📄 Posts
            </router-link>
            <router-link
                to="/write"
                class="text-text-body hover:text-brand-primary font-medium transition-colors"
                active-class="text-brand-primary font-bold"
            >
              ✍️ Write
            </router-link>
          </nav>

          <!-- Mode Badge (Standalone) -->
          <div class="px-3 py-1 bg-status-success-bg text-status-success text-sm font-medium rounded-full border border-status-success/20">
            📦 Standalone
          </div>
        </div>
      </div>
    </header>

    <!-- Embedded Mode Badge -->
    <div
        v-else
        class="bg-status-warning-bg border-b border-status-warning/20"
    >
      <div class="max-w-7xl mx-auto px-4 py-2">
        <p class="text-xs text-status-warning font-medium">
          🔗 Embedded Mode (Portal Shell)
        </p>
      </div>
    </div>

    <!-- Main Content -->
    <main :class="isEmbedded ? 'py-4' : 'py-8'">
      <router-view v-slot="{ Component }">
        <component :is="Component" v-if="Component" />

        <!-- 404 Error -->
        <div v-else class="max-w-5xl mx-auto px-6">
          <div class="bg-status-error-bg border border-status-error/20 rounded-lg p-8 text-center">
            <p class="text-xl text-status-error mb-4">
              ❌ 페이지를 찾을 수 없습니다: {{ route.path }}
            </p>
            <Button variant="primary" @click="$router.push('/')">
              홈으로 돌아가기
            </Button>
          </div>
        </div>
      </router-view>
    </main>

    <!-- Footer (Standalone 모드에서만) -->
    <footer
        v-if="!isEmbedded"
        class="bg-bg-card border-t border-border-default mt-auto"
    >
      <div class="max-w-7xl mx-auto px-4 py-6 text-center">
        <p class="text-sm text-text-meta">
          © 2025 Portal Universe Blog. All rights reserved.
        </p>
      </div>
    </footer>
  </div>
</template>
